services:
  postgres:
    image: postgres:15
    container_name: ContactManagement.Db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: setur
      POSTGRES_DB: ContactManagementDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
        
  rabbitmq:
    image: rabbitmq:4-management
    container_name: ContactManagement.RabbitMQ
    restart: always
    hostname: contact-management-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitMq-data:/var/lib/rabbitmq
      - rabbitMq-logs:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  apigateway:
    image: contactmanagement.apigateway
    build:
      context: .
      dockerfile: ContactManagement.ApiGateway/Dockerfile
      
volumes:
  postgres_data:
  rabbitMq-data:
  rabbitMq-logs:

