  
services:
  postgres:
    image: postgres:15
    container_name: ContactManagement.Db
    restart: always
    ports:
      - "5432:5432"
    networks:
      - contactmanagement
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: setur
      POSTGRES_DB: ContactManagementDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
        
  rabbitmq:
    image: rabbitmq:4-management
    container_name: ContactManagement.RabbitMQ
    restart: always
    hostname: contact-management-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - contactmanagement
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitMq-data:/var/lib/rabbitmq
      - rabbitMq-logs:/var/log/rabbitmq
      
  apigateway:
    build:
      context: .
      dockerfile: ContactManagement.ApiGateway/Dockerfile
    image: contactmanagement.apigateway
    networks:
      - contactmanagement
    depends_on:
      - contacts
      - reports
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8080:8080" # External HTTP access
      - "8081:8081" # External HTTPS access
        
  contacts:
    build:
      context: .
      dockerfile: Contacts/WebApi/Dockerfile
    image: contacts.webapi
    networks:
      - contactmanagement
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ContactsDb: "Host=postgres;Port=5432;Database=ContactsDb;Username=postgres;Password=setur"
      
  reports:
    build:
      context: .
      dockerfile: ContactReports/WebApi/Dockerfile
    image: reports.webapi
    networks:
      - contactmanagement
    depends_on:
      - postgres
      - rabbitmq
      - contacts
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__ContactsDb: "Host=postgres;Port=5432;Database=ContactsDb;Username=postgres;Password=setur"
      MessagingSettings__Host: "rabbitmq://rabbitmq/"
      MessagingSettings__Username: "guest"
      MessagingSettings__Password: "guest"
      ContactsServiceClientConfig__BaseUrl: "http://contacts:8080/"# Access by alias internally
      
volumes:
  postgres_data:
  rabbitMq-data:
  rabbitMq-logs:

networks:
  contactmanagement:
    driver: bridge

